version: "3"

services:

    db:
        container_name: mariadb10
        build: ./db
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 321564
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
            - 33000:3306

    adminer:
        build: ./adminer
        restart: always
        ports:
            - 8090:8080